# Generated by Django 3.0.7 on 2020-06-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_vouchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='expiry',
            field=models.DateTimeField(),
        ),
    ]
