# Generated by Django 3.0.7 on 2020-06-25 18:24

from django.db import migrations, models
import offer.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(default='offer_photo/default.jpg', upload_to='offer_photo/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('currency', models.SmallIntegerField(choices=[(0, 'INR'), (1, 'USD')], default=0)),
                ('validity', models.PositiveSmallIntegerField()),
                ('tag', models.TextField()),
                ('description', models.TextField()),
                ('terms', offer.utils.ListField()),
                ('guide', offer.utils.ListField()),
                ('own_use_only', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Offers',
            },
        ),
    ]
