# Generated by Django 3.0.7 on 2020-06-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
